### ISSUE TITLE
License for the pretrained models?

### ISSUE THREAD

**Issue by hbredin** [VoxBlink2/ScriptsForVoxBlink2#1]
Thanks for the great work! 

I understand that the dataset is licensed under CC BY-NC-SA 4.0.

However, what about the pretrained models? Do they allow commercial use? 
I am asking because I would like to possibly integrate them in pyannote OSS speaker diarization pipeline.

**Comment by VoxBlink2** [comment]
Sorry for a late reply. Unfortunately, the dataset used to train the model is subject to a license that restricts commercial use. Therefore, the model can only be used for academic research purposes and not for commercial applications.

**Comment by hbredin** [comment]
Makes sense, that's what I thought but I wanted to be 100% sure ;)
Thanks again for this awesome work!
