### ISSUE TITLE
Most of the videos are unavailable now

### ISSUE THREAD

**Issue by vanIvan** [VoxBlink2/ScriptsForVoxBlink2#10]
Thank you for your work, I've run dataloading of Voxblink2 dataset, on multiple machines (I've checked and they weren't been blocked). And after my script terminated, I calculated following downloading stats:
* Fully downloaded channels: ~7k / 111k 
* Downloaded at least one video for channel: ~25k / 111k, meaning that 86k are missing
This dataset decayed too fast for youtube based dataset.

**Comment by VoxBlink2** [comment]
Fine, we have seen the issues. Please fill in the blanks and we'll help you. https://docs.google.com/forms/d/e/1FAIpQLSdpQ67o3VjC_B6BGCicnf5gjLnQ2YxLgxIZCyyfYVoj8cniUQ/viewform

**Comment by vanIvan** [comment]
Hello! Could you please check the google form submission requests, I've submitted form sometime ago (2-3 weeks), but it seems no one checked it so far. Thank you in advance, and thanks for approving it first time, we have released [models](https://github.com/IDRnD/redimnet/blob/master/EVALUATION.md) trained on voxblink2 dataset.

**Comment by VoxBlink2** [comment]
Sorry for a late reply, please check your mailbox again. if there still no links, please contact with 2018302060299@whu.edu.cn with your gmail.

**Comment by vanIvan** [comment]
Perfect, thank you, I've received the link!
