### ISSUE TITLE
Meta-data about language information

### ISSUE THREAD

**Issue by ajk1402** [VoxBlink2/ScriptsForVoxBlink2#11]
Hello,

Thank you for providing such a extensive dataset, I would like to know meta-attribute  information regarding utterance to language mapping. Is there any file providing this information?

Thanks,
Ajinkya Kulkarni

**Comment by VoxBlink2** [comment]
Dear Ajinkya,

You can refer to the transcription results by Whisper or the meta-information in the Gdrive(https://drive.google.com/drive/folders/1lzumPsnl5yEaMP9g2bFbSKINLZ-QRJVP?usp=sharing)

Best regards

Yuke Lin


-----原始邮件-----
发件人:ajk1402 ***@***.***>
发送时间:2024-09-25 16:25:41 (星期三)
收件人: VoxBlink2/ScriptsForVoxBlink2 ***@***.***>
抄送: Subscribed ***@***.***>
主题: [VoxBlink2/ScriptsForVoxBlink2] Meta-data about language information (Issue #11)






Hello,

Thank you for providing such a extensive dataset, I would like to know meta-attribute information regarding utterance to language mapping. Is there any file providing this information?

Thanks,
Ajinkya Kulkarni

**Comment by ajk1402** [comment]
Can you please specify which tar file have language information ?

**Comment by VoxBlink2** [comment]
Hello,

Just unzip asr_res.tar.gz and you can find the language prediction derived from Whisper.

Best

Yuke Lin


-----原始邮件-----
发件人:ajk1402 ***@***.***>
发送时间:2024-09-26 18:50:48 (星期四)
收件人: VoxBlink2/ScriptsForVoxBlink2 ***@***.***>
抄送: VoxBlink2 ***@***.***>, Comment ***@***.***>
主题: Re: [VoxBlink2/ScriptsForVoxBlink2] Meta-data about language information (Issue #11)






Can you please specify which tar file have language information ?

**Comment by ajk1402** [comment]
okay thank you for quick reply.
