### ISSUE TITLE
“Download quota is exceeded” when download dataset

### ISSUE THREAD

**Issue by bhpugongying** [VoxBlink2/ScriptsForVoxBlink2#13]
Thank you very much for sharing dataset. But an error message "download quota is exceeded" occurs when I download the dataset using google drive. Could you please check if the error can be fixed?

**Comment by VoxBlink2** [comment]
Hello

The Google drive has a daily download quota and will be refreshed day after. To bypass this issue, you can make a copy and switch to another account or just wait till the refreshing done. Please let anybody know the download way of GDrive and I am going to delete the issue after. Thanks for understanding.

Best

Yuke Lin



-----原始邮件-----
发件人:"Bihui Chen" ***@***.***>
发送时间:2024-10-24 09:34:25 (星期四)
收件人: VoxBlink2/ScriptsForVoxBlink2 ***@***.***>
抄送: Subscribed ***@***.***>
主题: [VoxBlink2/ScriptsForVoxBlink2] “Download quota is exceeded” when download dataset (Issue #13)






Thank you very much for sharing dataset. But an error message "download quota is exceeded" occurs when I download the dataset. Could you please check if the error can be fixed?

**Comment by SimZhou** [comment]
I got the same issue here, which makes the whole downloading process super slow. 

"To bypass this issue, you can make a copy and switch to another account" 
The google drive (unlike other netdrives) doesn't allow making a copy, neither switching to another account, if the dataset is privately shared to another people. 
So ... it is not possible for us to 'make a copy' nor 'switch to another account' (the 'other account' won't have permission).

Again, many thanks to @VoxBlink2 who had shared this dataset to us. 

So if possible, is there any alternative ways for us to download?

**Comment by SimZhou** [comment]
https://www.reddit.com/r/google/comments/nfsgal/google_drive_download_quota_limit_exceeded_bypass/

Some tips to bypass google download quota limitation...but not working for big files like this...
