### ISSUE TITLE
How much storage space is needed to download the audio-only data？

### ISSUE THREAD

**Issue by SheenChi** [VoxBlink2/ScriptsForVoxBlink2#2]
Thank you very much for your great work!
Now I want download this data use for my work, and I want to now how much storage space the audio-only data occupies

**Comment by VoxBlink2** [comment]
We haven't calculated the space of raw audio, but raw video requires about 20TB and the final storage of audio-only VoxBlink2 needs 1.5TB. Hope it's helpful to you!
