### ISSUE TITLE
Distribution of video resolutions?

### ISSUE THREAD

**Issue by jinqiupeter** [VoxBlink2/ScriptsForVoxBlink2#4]
Dear Author,

First and foremost, thank you for open-sourcing such an outstanding dataset. Your work is greatly appreciated!

I noticed that the resolution of the videos is not mentioned in the accompanying paper. Could you kindly share this information? It would be beneficial for my research.

Thank you once again for your valuable contribution.

**Comment by VoxBlink2** [comment]
Sorry, we have not recorded the resolution of videos, we only record the bps as the reference of video qualities.
