### ISSUE TITLE
Can't download video 

### ISSUE THREAD

**Issue by DevKiHyun** [VoxBlink2/ScriptsForVoxBlink2#6]
<img width="889" alt="image" src="https://github.com/user-attachments/assets/1f4b539d-4a85-4026-b726-1f708cd97222">

Hello, 

Im trying to download video from url using your script code.

But, I got a trouble about the private download issue for some video.

How can i solve this problem?

thanks.

**Comment by VoxBlink2** [comment]
Sorry, we are powerless for such private videos, try to catch the error and just jump these videos.
