### ISSUE TITLE
WARNING: [youtube] xJl1Ie6PU4Y: nsig extraction failed: Some formats may be missing

### ISSUE THREAD

**Issue by Xiaobin-Rong** [VoxBlink2/ScriptsForVoxBlink2#9]
Hello, I encountered many warnings as described in the title when I ran `downloader.py`, is it normal?

**Comment by VoxBlink2** [comment]
Fine, we have seen the issues. Please fill in the blanks and we'll help you. https://docs.google.com/forms/d/e/1FAIpQLSdpQ67o3VjC_B6BGCicnf5gjLnQ2YxLgxIZCyyfYVoj8cniUQ/viewform

**Comment by Xiaobin-Rong** [comment]
@VoxBlink2  Thanks for your kind response! I have filled in the blanks. Will I receive the pre-downloaded data?

**Comment by VoxBlink2** [comment]
Please check the e-mail box you provide:)

**Comment by Xiaobin-Rong** [comment]
@VoxBlink2 
I have received the data, thank you! However, it seems that only audio data has been shared. May I request the video data as well?

**Comment by SheenChi** [comment]
@VoxBlink2 I have meet the same problem when I download the data and then have filled the blanks already. can you give me the pre-downloaded audio data too, thank you very much
